//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSAppWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> PatientId { get; set; }
        public long DoctorCharge { get; set; }
        public long RoomCharge { get; set; }
        public int NumberofDays { get; set; }
        public long LabChargeBill { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
