//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSAppWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTPatient
    {
        public int ID { get; set; }
        public Nullable<int> PatientId { get; set; }
        public System.DateTime Datee { get; set; }
        public Nullable<int> LabNo { get; set; }
    
        public virtual Laboratory Laboratory { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
